apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vol1
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
