apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: an-carla-cache # Change this to your initials
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
